.TH GOBYTE-CLI "1" "June 2016" "masterbit-cli 0.12"
.SH NAME
masterbit-cli \- a remote procedure call client for MasterBit Core. 
.SH SYNOPSIS
masterbit-cli [options] <command> [params] \- Send command to MasterBit Core. 
.TP
masterbit-cli [options] help \- Asks MasterBit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the masterbit-cli program. masterbit-cli is an RPC client used to send commands to MasterBit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBmasterbitd\fP, \fBmasterbit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
